### ISSUE TITLE
Doesn't work in private browsing.

### ISSUE THREAD

**Issue by jarredou** [igorlogius/load-background-tabs-on-select#2] opened 2021-08-05 11:05 UTC
If I'm browsing in private mode, this addon doesn't work. It opens a tab in background that isn't loaded, but when I click on the tab to activate it, nothing happens, the tab is blank.

**Comment by igorlogius** [comment] 2021-08-05 11:15
Interessting, i'll try to reproduce it. 

If this is actually the case, this might be a bug within firefox, since i dont think private and normal mode should have a different behaviour ... when an addon has been activated for both.  

I'll report back with my finding.

**Comment by igorlogius** [comment] 2021-08-05 11:28
A could consistently reproduce the issue with Fx 90.0.2 

Sadly since i dont know what the difference between the private and normal mode in this case are i am unable to debug the issue.  - At least no obvious error is thrown and there doesnt seem to be documentation on this topic within the web-ext docs. 

Guss we'll have to open an bug ticket something like

"different behaviour of addon dontLoadBackgroundTabs  in private browsing mode" 
 
on the  bugzilla bugtracker  (https://bugzilla.mozilla.org/index.cgi)

@jarredou:  Do you want to open the issue there or should i take care of it?

**Comment by jarredou** [comment] 2021-08-05 11:37
I'm not used to report bugs with bugzilla, if you can take care it, it would be better, I think.
Thanks a lot !

**Comment by igorlogius** [comment] 2021-08-10 10:52
Update: issue has been accepted and could be reproduced with FF 90,91,92,93. Triage  is pending ...

**Comment by igorlogius** [comment] 2021-08-17 16:17
The bug has been fixed in Firefox 93.0a1, 

That means, that the bugfix should enter/merge into  the Release channel  on 2021-10-04
(ref. https://wiki.mozilla.org/Release_Management/Calendar)

Nothing else to do here i guess.

**Closed by igorlogius** 2021-08-17 16:17 UTC
Labels: firefox bug
